version: '3.8'

services:
  api:
    depends_on:
      - db
    build: ./
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASS=password
      - MYSQL_DB=main
    ports:
      - '8080:8080'
    links:
      - "db:database"
    restart: always
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"